// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhwDv8G2DDxsvUhNbCao8R3akW2ZMHv58',
    appId: '1:989517158856:web:7f6a297e68ad12837008fd',
    messagingSenderId: '989517158856',
    projectId: 'klik-hemat',
    authDomain: 'klik-hemat.firebaseapp.com',
    databaseURL: 'https://klik-hemat-default-rtdb.firebaseio.com',
    storageBucket: 'klik-hemat.appspot.com',
    measurementId: 'G-7L96W8NZZF',
  );



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwYSIxb4ltY_48g5-zGkf1KFwf7k2gcIQ',
    appId: '1:989517158856:android:ca8acbedd51279737008fd',
    messagingSenderId: '989517158856',
    projectId: 'klik-hemat',
    databaseURL: 'https://klik-hemat-default-rtdb.firebaseio.com',
    storageBucket: 'klik-hemat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwDv8G2DDxsvUhNbCao8R3akW2ZMHv58',
    appId: '1:989517158856:ios:65634e1b9744295d7008fd',
    messagingSenderId: '989517158856',
    projectId: 'klik-hemat',
    databaseURL: 'https://klik-hemat-default-rtdb.firebaseio.com',
    storageBucket: 'klik-hemat.appspot.com',
    iosBundleId: 'com.example.klikhemat.klikHemat',
  );

}